services:
  app:
    build: ./app
    command: > 
            bash -c "python manage.py wait_for_db && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.dev
  db:
    image: postgres:16-alpine3.21
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=books
      - POSTGRES_DB=books_dev

volumes:
  postgres_data: